site_name: Crossover Explorer

theme:
  name: "readthedocs"

extra_css:
  - css/xo.css
  
plugins:
  - search
  - mkdocstrings

nav:
  - "Home":
    - "Getting Started": index.md
  - "Running the Applications":
    - peaks.md
    - gui.md
    - vis.md
  - "Developer":
    - "Source Directory": modules.md
    - "Modules":
      - "xo": main.md
      - "filters": filters.md
      - "peaks": peaks_module.md
      - "gui":
        - "gui": gui_module.md
        - "Widget Classes": widgets.md
        - "Filter Widgets": filterbox.md
        - "PeakViewerApp": app.md
        - "Chromosome Display": chromosomes.md
        - "Callback Functions": callbacks.md
        - "Creating and Starting the GUI": start_app.md
      - "vis": vis_module.md
